### ISSUE TITLE
indexERROR

### ISSUE THREAD

**Issue by yoyok7l** [eblio/dofus-treasure-finder#1]
Lorsque je clique sur démarrer je recoit le probleme suivant : 
Résultat
Aucune solution : (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x0000019BC1CCA800>)
aucune idée ? svp 
et merci good job.
![what](https://user-images.githubusercontent.com/89700744/131224125-721dc247-1bf1-4109-bd4b-2af81800b25d.png)

**Comment by eblio** [comment]
Salut, c'est l'erreur de base quand il arrive pas à lire la position de ton personnage sur l'écran. Je sors une nouvelle version dans la journée pour essayer de rendre ça un peu plus fiable (entre autre). 

Parfois, se décaler d'une map suffit à régler le problème. Pense aussi à laisser les barres noires sur les côtés ça l'aide un peu.

**Comment by eblio** [comment]
Plutôt demain la mise à jour. :p
