### ISSUE TITLE
Interaction with dofusDB

### ISSUE THREAD

**Issue by Aztgod** [eblio/dofus-treasure-finder#3]
Can you explain a bit more how does it interact with dofusDB to get the hints?

**Comment by eblio** [comment]
The script uses [Selenium](https://www.selenium.dev/) to interact with the web page like a human would. I haven't found a way to properly generate a token to interact with the DofusDB API, it should be possible though (maybe requiring a bit of human interaction). 

You can see Selenium in action by cloning the repository and providing all required dependencies. Note that the `README.md` isn't up to date. The latest code updates made the tool really efficient.

I'll keep this open in case you need further information.
